### ISSUE TITLE
so端如何解密，能否放一下源码？

### ISSUE THREAD

**Issue by liana101** [hustwyk/AndroidSoEncodeSection#1]
so端如何解密，能否放一下源码？谢谢

**Comment by hustwyk** [comment]
赵四原来的CSDN的博客删了，那就看他的另一个博客里的[《Android逆向之旅—基于对so中的函数加密技术实现so加固》](http://www.520monkey.com/archives/565)，so端的代码都在里面

其实这个加解密很简单只用了取反，主要是学习这个过程
